import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../app/providers.dart';
import '../../../core/utils/validators.dart';
import '../data/user_model.dart';
class LoginScreen extends ConsumerStatefulWidget { const LoginScreen({super.key}); @override ConsumerState<LoginScreen> createState()=>_LoginScreenState(); }
class _LoginScreenState extends ConsumerState<LoginScreen> { final _form=GlobalKey<FormState>(); final _email=TextEditingController(); final _password=TextEditingController(); bool _loading=false; @override void dispose(){_email.dispose();_password.dispose();super.dispose();} Future<void> _signIn() async {if(!_form.currentState!.validate())return;setState(()=>_loading=true);try{final user=await ref.read(authRepositoryProvider).signIn(_email.text.trim(),_password.text);if(mounted)Navigator.pushReplacementNamed(context,'/${user.role.name}');}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر تسجيل الدخول: $e')));}finally{if(mounted)setState(()=>_loading=false);}}
@override Widget build(BuildContext context)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:480),child:Padding(padding:const EdgeInsets.all(24),child:Form(key:_form,child:ListView(shrinkWrap:true,children:[const Icon(Icons.school,size:72),const SizedBox(height:16),Text('أهلاً بعودتك',textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:24),TextFormField(controller:_email,validator:Validators.email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'البريد الإلكتروني')),const SizedBox(height:12),TextFormField(controller:_password,validator:Validators.password,obscureText:true,decoration:const InputDecoration(labelText:'كلمة المرور')),Align(alignment:Alignment.centerLeft,child:TextButton(onPressed:()=>Navigator.pushNamed(context,'/forgot-password'),child:const Text('نسيت كلمة المرور؟'))),FilledButton(onPressed:_loading?null:_signIn,child:Text(_loading?'جارٍ تسجيل الدخول…':'تسجيل الدخول')),TextButton(onPressed:()=>Navigator.pushNamed(context,'/register'),child:const Text('إنشاء حساب جديد'))])))))); }
class RegisterScreen extends ConsumerStatefulWidget { const RegisterScreen({super.key}); @override ConsumerState<RegisterScreen> createState()=>_RegisterScreenState(); }
class _RegisterScreenState extends ConsumerState<RegisterScreen> { final _form=GlobalKey<FormState>(); final _name=TextEditingController(),_email=TextEditingController(),_phone=TextEditingController(),_password=TextEditingController(),_organization=TextEditingController(); UserRole _role=UserRole.student; bool _loading=false; @override void dispose(){for(final c in [_name,_email,_phone,_password,_organization]){c.dispose();}super.dispose();} Future<void> _register() async {if(!_form.currentState!.validate())return;setState(()=>_loading=true);try{final user=await ref.read(authRepositoryProvider).register(name:_name.text.trim(),email:_email.text.trim(),password:_password.text,phone:_phone.text.trim(),role:_role,profile:_role==UserRole.student?{'university':_organization.text.trim()}: {'specialization':_organization.text.trim()});if(mounted)Navigator.pushNamedAndRemoveUntil(context,'/${user.role.name}',(_)=>false);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('تعذر إنشاء الحساب: $e')));}finally{if(mounted)setState(()=>_loading=false);}} @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('إنشاء حساب')),body:Padding(padding:const EdgeInsets.all(20),child:Form(key:_form,child:ListView(children:[DropdownButtonFormField(value:_role,items:const [DropdownMenuItem(value:UserRole.student,child:Text('طالب')),DropdownMenuItem(value:UserRole.advisor,child:Text('مستشار'))],onChanged:(v)=>setState(()=>_role=v!),decoration:const InputDecoration(labelText:'نوع الحساب')),const SizedBox(height:12),...[_field(_name,'الاسم الكامل'),_field(_email,'البريد الإلكتروني',validator:Validators.email),_field(_phone,'رقم الهاتف'),_field(_password,'كلمة المرور',validator:Validators.password,secret:true),_field(_organization,_role==UserRole.student?'الجامعة':'التخصص المهني')],FilledButton(onPressed:_loading?null:_register,child:Text(_loading?'جارٍ الإنشاء…':'إنشاء الحساب'))])))); Widget _field(TextEditingController controller,String label,{String? Function(String?)? validator,bool secret=false})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextFormField(controller:controller,validator:validator??(v)=>Validators.required(v,label:label),obscureText:secret,decoration:InputDecoration(labelText:label))); }
class ForgotPasswordScreen extends ConsumerStatefulWidget {const ForgotPasswordScreen({super.key});@override ConsumerState<ForgotPasswordScreen> createState()=>_ForgotPasswordScreenState();} class _ForgotPasswordScreenState extends ConsumerState<ForgotPasswordScreen>{final _email=TextEditingController();final _form=GlobalKey<FormState>();@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(),body:Padding(padding:const EdgeInsets.all(24),child:Form(key:_form,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('استعادة كلمة المرور'),const SizedBox(height:16),TextFormField(controller:_email,validator:Validators.email,decoration:const InputDecoration(labelText:'البريد الإلكتروني')),const SizedBox(height:16),FilledButton(onPressed:()async{if(_form.currentState!.validate()){await ref.read(authRepositoryProvider).resetPassword(_email.text.trim());if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم إرسال رابط إعادة التعيين.')));}},child:const Text('إرسال الرابط'))])));}
